CREATE TABLE usuario
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome   VARCHAR(255) NOT NULL,
    email  VARCHAR(255) NOT NULL,
    senha  VARCHAR(255) NOT NULL,
    cep    VARCHAR(9),
    cidade VARCHAR(255),
    uf     VARCHAR(2),
    papel  VARCHAR(20)  NOT NULL DEFAULT 'USER',
    CONSTRAINT pk_usuario PRIMARY KEY (id),
    CONSTRAINT uk_usuario_email UNIQUE (email)
);
