CREATE TABLE servico
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    prestador_id BIGINT         NOT NULL,
    titulo       VARCHAR(255)   NOT NULL,
    descricao    VARCHAR(1000),
    categoria    VARCHAR(100),
    preco        NUMERIC(10, 2) NOT NULL,
    situacao     VARCHAR(20)    NOT NULL DEFAULT 'ATIVO',
    CONSTRAINT pk_servico PRIMARY KEY (id),
    CONSTRAINT fk_servico_on_prestador FOREIGN KEY (prestador_id) REFERENCES usuario (id)
);
