CREATE TABLE contratacao
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    servico_id       BIGINT      NOT NULL,
    contratante_id   BIGINT      NOT NULL,
    situacao         VARCHAR(20) NOT NULL DEFAULT 'SOLICITADA',
    data_contratacao TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_contratacao PRIMARY KEY (id),
    CONSTRAINT fk_contratacao_on_servico FOREIGN KEY (servico_id) REFERENCES servico (id),
    CONSTRAINT fk_contratacao_on_contratante FOREIGN KEY (contratante_id) REFERENCES usuario (id)
);
